# Generated by Django 5.1.2 on 2024-10-20 07:42

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_comment"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="comment",
            new_name="post_commen_created_409d9a_idx",
            old_name="post_comment_created_409d9a_idx",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
